// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace ATFXamarin.Touch
{
	public partial class EngagementCell : UITableViewCell
	{
		public EngagementCell (IntPtr handle) : base (handle)
		{
		}
	}
}
